version: '3.8'
services:
  server:
    container_name: nestegg-lending
    ports:
    - 18080:8080
    build: .
    depends_on:
    - db

  db:
    container_name: nestegg-lending
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - ../lending-postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: pub